### ISSUE TITLE
Implementing SaveCookies and RestoreCookies does not prevent unnecessary logins

### ISSUE THREAD

**Issue by DuncWatts** [AdrianJSClark/aydsko-iracingdata#186]
As per #185 I'm implementing this library within an Azure function application.

Each call to an endpoint results in a new instance of the function class, and therefore a fresh DataClient instance.  To prevent this from then reauthenticating on every invocation I have implemented the SaveCookies and RestoreCookies Funcs on the iRacingDataClientOptions property.

With these specified the LoginInternalAsync method will restore the CookieContainer, however it still runs through the auth process, leading to unnecessary calls to the auth endpoint.

I've added a workaround to mark it as logged in if a CookieContainer has been restored.  Happy to create a PR if this is an acceptable approach.

```
            if (options.RestoreCookies is not null
                && options.RestoreCookies() is CookieCollection savedCookies)
            {
                cookieContainer.Add(savedCookies);

                IsLoggedIn = true;
                return;
            }
```

**Comment by AdrianJSClark** [comment]
Thanks for lodging this issue! Your suggested fix should be good as a first step to properly resolve this problem.

I think there will need to be additional consideration given to error handling, however, to ascertain if an error indicating authentication has failed needs to also alter the `IsLoggedIn` property.

I'll probably have some time to look at this this week.

**Comment by tobiaszuercher** [comment]
@AdrianJSClark any update? do you need any help on this?

**Comment by AdrianJSClark** [comment]
Apologies, had some busy stuff going on in my home life and work life, so haven't got to this yet.

@tobiaszuercher, the thinking around things being internal was to guide people to the interface and make it obvious that I wasn't planning for extending. That was probably a bit selfish to be honest, because in the back of my mind I knew I could always either change it or just put my extension internal as well. I'd happily accept any changes to open the library up to make it easier to extend and use. Just open a new issue or PR (so we don't hijack Duncan's issue here).

Help is also welcome on this issue. I've un-assigned myself so feel free to do some work. I definitely planned to get things underway a couple of weeks ago but, as I said above, life interrupted.
